export const SCREENS = [
  { id:"SCR-001", name:"Corner Brew — Oxford St",    city:"London",     neighbourhood:"Oxford Street",      status:"live",    impressions:84200,  revenue:1240, owner:"Corner Brew Coffee",    campaigns:2, cpm:4.80, maxDuration:15 },
  { id:"SCR-002", name:"Canary Wharf Plaza",          city:"London",     neighbourhood:"Canary Wharf",       status:"live",    impressions:210000, revenue:3880, owner:"Greenfield Properties", campaigns:2, cpm:5.20, maxDuration:30 },
  { id:"SCR-003", name:"Shoreditch Stop",             city:"London",     neighbourhood:"Bethnal Green",      status:"pending", impressions:0,       revenue:0,   owner:"Urban Spaces Group",    campaigns:0, cpm:4.20, maxDuration:20 },
  { id:"SCR-004", name:"Piccadilly Gardens",          city:"Manchester", neighbourhood:"City Centre",        status:"live",    impressions:142000, revenue:2100, owner:"MCR Transit Auth.",     campaigns:2, cpm:4.20, maxDuration:20 },
  { id:"SCR-006", name:"New Street Station",          city:"Birmingham", neighbourhood:"City Centre",        status:"live",    impressions:188000, revenue:2900, owner:"Network Rail",          campaigns:1, cpm:4.50, maxDuration:25 },
  { id:"SCR-008", name:"King & Bay — TTC Shelter",   city:"Toronto",    neighbourhood:"Financial District", status:"live",    impressions:162000, revenue:2400, owner:"Slate Asset Mgmt",      campaigns:2, cpm:4.20, maxDuration:30 },
  { id:"SCR-009", name:"Queen West — Ossington",     city:"Toronto",    neighbourhood:"West Queen West",    status:"live",    impressions:58000,  revenue:980,  owner:"Ossington Hospitality", campaigns:1, cpm:3.80, maxDuration:15 },
];

export const INIT_CAMPAIGNS = [
  { id:"BK-001", advertiser:"Pret A Manger", category:"Food & Beverage",  screenId:"SCR-001", screen:"Corner Brew — Oxford St",    city:"London",     budget:480,  spent:312,  impressions:12400, scans:42,  status:"active",    start:"2026-03-21", end:"2026-04-21", days:["Mon","Tue","Wed","Thu","Fri"], timeStart:"07:00", timeEnd:"11:00", slots:8,  duration:10, headline:"Start Your Morning Right", color:"#f59e0b", destination:"https://pret.com/order" },
  { id:"BK-002", advertiser:"Nike",           category:"Fashion & Retail", screenId:"SCR-002", screen:"Canary Wharf Plaza",          city:"London",     budget:2200, spent:1480, impressions:44200, scans:127, status:"active",    start:"2026-03-15", end:"2026-04-15", days:["Mon","Tue","Wed","Thu","Fri","Sat"], timeStart:"08:00", timeEnd:"20:00", slots:20, duration:30, headline:"Just Do It.",              color:"#ffffff",   destination:"https://nike.com/spring" },
  { id:"BK-003", advertiser:"Lloyds Bank",   category:"Finance & Banking", screenId:"SCR-002", screen:"Canary Wharf Plaza",          city:"London",     budget:1440, spent:0,    impressions:0,     scans:0,   status:"scheduled", start:"2026-04-01", end:"2026-04-30", days:["Mon","Tue","Wed","Thu","Fri"],       timeStart:"06:00", timeEnd:"09:00", slots:12, duration:20, headline:"Banking Built for You",     color:"#22c55e",   destination:"https://lloydsbank.com" },
  { id:"BK-005", advertiser:"Caffè Nero",    category:"Food & Beverage",  screenId:"SCR-004", screen:"Piccadilly Gardens",           city:"Manchester", budget:620,  spent:290,  impressions:18800, scans:28,  status:"active",    start:"2026-03-18", end:"2026-04-18", days:["Mon","Tue","Wed","Thu","Fri"],       timeStart:"07:00", timeEnd:"10:00", slots:10, duration:12, headline:"Your Perfect Morning Cup",  color:"#d97706",   destination:"https://caffenero.com" },
  { id:"BK-007", advertiser:"John Lewis",    category:"Fashion & Retail", screenId:"SCR-006", screen:"New Street Station",           city:"Birmingham", budget:1800, spent:1100, impressions:38400, scans:94,  status:"active",    start:"2026-03-20", end:"2026-04-20", days:["Mon","Tue","Wed","Thu","Fri","Sat"], timeStart:"09:00", timeEnd:"21:00", slots:18, duration:25, headline:"Never Knowingly Undersold", color:"#60a5fa",   destination:"https://johnlewis.com" },
  { id:"BK-008", advertiser:"Tim Hortons",   category:"Food & Beverage",  screenId:"SCR-008", screen:"King & Bay — TTC Shelter",    city:"Toronto",    budget:720,  spent:390,  impressions:21400, scans:38,  status:"active",    start:"2026-03-21", end:"2026-04-21", days:["Mon","Tue","Wed","Thu","Fri"],       timeStart:"06:00", timeEnd:"10:00", slots:12, duration:10, headline:"Always Fresh.",             color:"#c8102e",   destination:"https://timhortons.ca" },
  { id:"BK-009", advertiser:"MLSE",           category:"Entertainment",    screenId:"SCR-008", screen:"King & Bay — TTC Shelter",    city:"Toronto",    budget:1200, spent:620,  impressions:18200, scans:64,  status:"active",    start:"2026-03-21", end:"2026-04-30", days:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], timeStart:"17:00", timeEnd:"23:00", slots:10, duration:20, headline:"Game Night.",              color:"#00205b",   destination:"https://scotiabankarena.com" },
  { id:"BK-010", advertiser:"Shopify",        category:"Technology",       screenId:"SCR-009", screen:"Queen West — Ossington",      city:"Toronto",    budget:960,  spent:0,    impressions:0,     scans:0,   status:"paused",    start:"2026-04-01", end:"2026-04-30", days:["Mon","Tue","Wed","Thu","Fri"],       timeStart:"08:00", timeEnd:"18:00", slots:8,  duration:15, headline:"Build Your Business.",     color:"#96bf48",   destination:"https://shopify.com" },
];

export const CATEGORIES = ["Food & Beverage","Fashion & Retail","Finance & Banking","Health & Fitness","Entertainment","Technology","Travel & Tourism","Automotive","Real Estate"];
export const DAYS = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
export const HOURS = Array.from({length:24},(_,i)=>`${String(i).padStart(2,"0")}:00`);

export const SCAN_DATA = [
  {id:"SCN-001",ts:"2026-03-29T08:14:22Z",advertiser:"Pret A Manger",screen:"Corner Brew — Oxford St",city:"London",device:"iPhone 15",age:"25-34",gender:"Female",consent:true,email:"alice@example.com"},
  {id:"SCN-002",ts:"2026-03-29T08:22:11Z",advertiser:"Pret A Manger",screen:"Corner Brew — Oxford St",city:"London",device:"Samsung Galaxy S24",age:"35-44",gender:"Male",consent:false,email:null},
  {id:"SCN-003",ts:"2026-03-29T09:05:44Z",advertiser:"Nike",screen:"Canary Wharf Plaza",city:"London",device:"iPhone 14 Pro",age:"18-24",gender:"Male",consent:true,email:"ben.k@email.com"},
  {id:"SCN-004",ts:"2026-03-29T09:18:33Z",advertiser:"Nike",screen:"Canary Wharf Plaza",city:"London",device:"Pixel 8",age:"25-34",gender:"Female",consent:true,email:"priya@email.com"},
  {id:"SCN-005",ts:"2026-03-29T10:02:17Z",advertiser:"Caffè Nero",screen:"Piccadilly Gardens",city:"Manchester",device:"iPhone 13",age:"45-54",gender:"Female",consent:false,email:null},
  {id:"SCN-006",ts:"2026-03-29T10:44:08Z",advertiser:"John Lewis",screen:"New Street Station",city:"Birmingham",device:"iPad Pro",age:"35-44",gender:"Male",consent:true,email:"mark.t@email.com"},
  {id:"SCN-007",ts:"2026-03-29T11:29:55Z",advertiser:"Tim Hortons",screen:"King & Bay — TTC Shelter",city:"Toronto",device:"iPhone 15 Pro",age:"25-34",gender:"Male",consent:true,email:"jay.m@email.com"},
  {id:"SCN-008",ts:"2026-03-29T12:10:22Z",advertiser:"MLSE",screen:"King & Bay — TTC Shelter",city:"Toronto",device:"Samsung Galaxy A54",age:"18-24",gender:"Male",consent:false,email:null},
  {id:"SCN-009",ts:"2026-03-29T13:05:40Z",advertiser:"Nike",screen:"Canary Wharf Plaza",city:"London",device:"iPhone 15",age:"25-34",gender:"Female",consent:true,email:"sara.l@email.com"},
  {id:"SCN-010",ts:"2026-03-29T14:22:19Z",advertiser:"Pret A Manger",screen:"Corner Brew — Oxford St",city:"London",device:"Pixel 7",age:"55+",gender:"Female",consent:true,email:"ruth.h@email.com"},
];
