export const FAQS = [
  ['Which cities is AdGrid available in?',
    "We're launching in Toronto and Vancouver, with more Canadian cities planned as we onboard operators. Join the waitlist below if you're elsewhere — we'll reach out as we expand."],
  ['What screens qualify as an AdGrid display?',
    'Any landscape digital screen with an internet connection — a commercial display, a spare TV, or existing digital signage. Connect it in minutes with our lightweight display player; no proprietary hardware to buy.'],
  ['How much does AdGrid take, and how do payouts work?',
    'AdGrid takes a 12% platform fee; you keep 40% of net ad spend on every screen you list. Payouts are automatic via Stripe Connect on a schedule shown in your dashboard — no invoicing, no chasing payment.'],
  ['Do I have to sign a contract or pay anything upfront?',
    'No. Listing your screens is free with no long-term contract — pause or remove your inventory anytime.'],
  ['What control do I have over what plays on my screen?',
    "Full control. Approve or reject every ad before it airs, block entire categories or specific competitors, and set blackout hours when you don't want any ads running at all."],
  ['Is there a minimum ad spend for advertisers?',
    'No minimums and no long-term contracts. You see the exact price per slot before you book, and you pay only for time that actually plays.'],
  ['How do I know my campaign actually ran?',
    'Every campaign includes playback logs proving when and where your ad ran, plus a unique QR code so you can track scans by screen and by hour.'],
  ['What happens if I cancel a campaign?',
    'Cancel before any impressions are served and you get a full refund within 5–10 business days. Once impressions start, charges are final.'],
];
