-- ============================================================
-- Replaces lift_stats (see 20260815000000_holdout_lift_testing.sql).
--
-- lift_stats compared scan rates between exposed and control screens, but
-- control screens are excluded from serving (display-feed) by design, so
-- they never generate ad_plays / campaign_delivery_daily rows -- the
-- control side of that comparison was structurally always empty. See
-- Revision 1 in docs/superpowers/specs/2026-08-14-holdout-lift-testing-design.md.
--
-- This view compares exposed screens' ACTUAL delivered rate (measured
-- plays, from campaign_delivery_daily) against control screens' AMBIENT
-- audience rate (screen_audience_index, generated by the CV camera
-- regardless of what plays -- the only signal that exists for a screen
-- that never served this campaign), both expressed in people-per-minute
-- so they're directly comparable. Restricted to the campaign's own
-- schedule_days/time_start/time_end window so it's a fair comparison
-- against the same time-of-week the exposed screens actually played.
--
-- Known limitation: the hour-window filter below does not handle an
-- overnight schedule (time_start > time_end) -- accepted v1 scope, see
-- the plan's Context section.
-- ============================================================

DROP VIEW IF EXISTS public.lift_stats;

CREATE OR REPLACE VIEW public.delivery_check_stats
WITH (security_invoker = true) AS
WITH day_map(day_name, dow) AS (
  VALUES ('Sun',0),('Mon',1),('Tue',2),('Wed',3),('Thu',4),('Fri',5),('Sat',6)
),
exposed AS (
  SELECT
    d.campaign_id,
    sum(d.impressions)                                    AS exposed_impressions,
    sum(d.completed_plays * b.duration) / 60.0             AS exposed_play_minutes
  FROM public.campaign_delivery_daily d
  JOIN public.campaign_screens cs
    ON cs.campaign_id = d.campaign_id AND cs.screen_id = d.screen_id AND cs.is_control = false
  JOIN public.bookings b ON b.id = d.campaign_id
  GROUP BY d.campaign_id
),
control_windows AS (
  SELECT
    b.id AS campaign_id,
    dm.dow,
    extract(hour FROM b.time_start::time)::int AS start_hour,
    extract(hour FROM b.time_end::time)::int   AS end_hour
  FROM public.bookings b
  CROSS JOIN LATERAL unnest(b.schedule_days) AS sd(day_name)
  JOIN day_map dm ON dm.day_name = sd.day_name
  WHERE b.holdout_enabled = true
),
control AS (
  SELECT
    cw.campaign_id,
    avg(ai.people_per_min) AS control_people_per_min
  FROM control_windows cw
  JOIN public.campaign_screens cs
    ON cs.campaign_id = cw.campaign_id AND cs.is_control = true
  JOIN public.screen_audience_index ai
    ON ai.screen_id = cs.screen_id
   AND ai.dow = cw.dow
   AND ai.hour BETWEEN cw.start_hour AND cw.end_hour
  GROUP BY cw.campaign_id
)
SELECT
  coalesce(exposed.campaign_id, control.campaign_id)        AS campaign_id,
  exposed.exposed_impressions,
  exposed.exposed_play_minutes,
  CASE WHEN exposed.exposed_play_minutes > 0
       THEN exposed.exposed_impressions / exposed.exposed_play_minutes
       ELSE NULL END                                        AS exposed_rate,
  control.control_people_per_min                             AS control_rate
FROM exposed
FULL OUTER JOIN control ON control.campaign_id = exposed.campaign_id;

GRANT SELECT ON public.delivery_check_stats TO authenticated, service_role;
